import React from "react";

const StructuredGiving = () => {
    return (
        <article id="417e32d6-48ed-4dfc-aed6-8b9453fed624" className="page sans"><div className="page-body"><p id="635e6bfa-db95-4f8a-8333-0efb87dab76b" className="">When a donor gives assets to a friend, family member, charity, business partner, or some other organization, the donor might want to structure the distribution across time. The donor might want to ensure a steady stream of support, rather than one lump sum. Similarly, a donor might want to make a gift subject to some conditions. A dtrust with control keys can manage the ultimate enjoyment of a gift. A dtrust enables the donor to structure both the timeliness and ultimate control of gifts. </p><p id="558de32f-546d-40a0-a13b-c740968a8b63" className="">
</p><p id="2eecf805-a5c4-4c33-b083-c93b3c6ca808" className="">For example, the people in many regions practice dowry and dowers. A dtrust could be either a dowry or a dower to ensure payments long into the future. For another example, a donor might want to support a student, a charity, or university with scheduled future payments, but only if certain behavioral expectations or usage expectations are met. The donor could retain a control key and revoke the dtrust if the donor&#x27;s expectations are not met. </p><p id="d3d6112c-e2c8-4d56-b8b1-9aec61f2de92" className="">
</p><ul id="78bbaab2-e614-4278-ab2b-b170d823d2f8" className="toggle"><li><details open=""><summary><strong>Structured Giving Hypothetical</strong></summary><p id="7efa35b4-15d4-47be-972c-9f6392724a90" className="">A is excited to marry her fiancee B. In this country, a bride&#x27;s family typically delivers a dowry to the groom or his family. Usually, the dowry is given with physical assets such as gold, jewelry, and other movable property. A and B love each other very much, but A&#x27;s family is concerned that B&#x27;s family might squander the dowry money, because there is a pesky relative with a gambling problem. As A&#x27;s family prepares to send their daughter into marriage, A&#x27;s family decides to use a dtrust to deliver the dowry, rather than gold, jewelry, and other physical property. With a dtrust, B could receive the dowry over time, have better control over the value, and ensure that the value goes into the young family. </p><p id="605d1ff0-58bf-41a2-8c07-282021b9397e" className="">A&#x27;s family visits <a href="http://dtrust.io">dtrust.io</a> and clicks on &quot;Start&quot;. They click &quot;Form a dtrust&quot;. Now they are going to specify the dtrust. A&#x27;s family decides not to keep any control keys—this is an irrevocable dtrust. There is no going back. It is a meaningful contribution by A&#x27;s family to the new couple. A&#x27;s family creates one beneficiary wallet and gives the private key to control that wallet to both A and B. A&#x27;s family decides to also create a trustee wallet that receives no fee, but receives one control key that allows the key holder to revoke the dtrust to return the assets to A&#x27;s family&#x27;s wallet. A&#x27;s family could give keys to control the trustee wallet to A, B, or both, but they decide to give to to only A. For the distribution schedule, A&#x27;s family schedules regular payments each month long into the future. A&#x27;s family clicks &quot;Form dtrust&quot; and funds the dtrust with digital assets. </p><p id="ab3f9bb9-9813-45f7-af65-b1a1e6705929" className="">A and B have a happy wedding and begin their new lives together. A&#x27;s family has successfully contributed to the new couple in such a way that facilitates a successful long-term marriage, protects the dowry from the groom&#x27;s family, and provides some control to A over the dowry assets.</p></details></li></ul></div></article>
    )
}

export default StructuredGiving;